# Converts a binary file into a C++ header exposing the bytes as an array.
# Usage:
#   cmake -DEMBED_INPUT=<file> -DEMBED_OUTPUT=<header> -DEMBED_SYMBOL=<name>
#         -P embed_binary.cmake
# The generated header defines:
#   inline const unsigned char <name>[] = {...};
#   inline const unsigned long long <name>_size = ...;

if(NOT EMBED_INPUT OR NOT EMBED_OUTPUT OR NOT EMBED_SYMBOL)
    message(FATAL_ERROR "embed_binary.cmake needs EMBED_INPUT, EMBED_OUTPUT, EMBED_SYMBOL")
endif()

file(READ "${EMBED_INPUT}" hex_bytes HEX)
file(SIZE "${EMBED_INPUT}" byte_count)

# 0x00,0x01,... with line breaks every 32 bytes to keep the header editable.
string(REGEX REPLACE "(..)" "0x\\1," hex_bytes "${hex_bytes}")
string(REGEX REPLACE "((0x..,){32})" "\\1\n    " hex_bytes "${hex_bytes}")

file(WRITE "${EMBED_OUTPUT}" "// Generated by embed_binary.cmake from ${EMBED_INPUT}. Do not edit.
#pragma once

inline const unsigned char ${EMBED_SYMBOL}[] = {
    ${hex_bytes}
};
inline const unsigned long long ${EMBED_SYMBOL}_size = ${byte_count}ull;
")
